### ISSUE TITLE
Figures missing

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshopwhepp-lesson-physics-objects#1]
The figures in the local repository are missing and do not show e.g. in 

https://cms-opendata-workshop.github.io/workshopwhepp-lesson-physics-objects/01-introduction/index.html

**Comment by jmhogan** [comment]
Should be fixed with [ef5be0c](https://github.com/cms-opendata-workshop/workshopwhepp-lesson-physics-objects/commit/ef5be0cbbfe11a001ff63c44ddf882cb54fcdfe3) -- I got assets/img/ but not fig/
